const BRAND = [16, 24, 40];
const ACCENT = [17, 159, 157];
const STATUSES = ['PRESENT_IN_CHURCH', 'JOINED_ONLINE', 'ABSENT', 'SICK', 'NEEDS_PRAYER', 'TRAVELLING', 'WORKING', 'FAMILY_COMMITMENT', 'OTHER'];
const ATTENTION = ['ABSENT', 'SICK', 'NEEDS_PRAYER'];

const words = (value, fallback = 'None') => value
  ? String(value).toLowerCase().split('_').map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')
  : fallback;

const dateText = (value, includeTime = false) => {
  if (!value) return 'N/A';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'N/A';
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
    ...(includeTime ? { hour: '2-digit', minute: '2-digit' } : {})
  }).format(date);
};

const filePart = (value, fallback) => String(value || fallback).trim().toLowerCase()
  .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || fallback;

const fileName = ({ serviceName, startDate, endDate, extension }) => {
  const rangeEnd = endDate && endDate !== startDate ? `-to-${filePart(endDate, 'date')}` : '';
  return `${filePart(serviceName, 'service')}-${filePart(startDate, 'all-dates')}${rangeEnd}-attendance.${extension}`;
};

const householdValues = (row) => {
  const number = (group, gender) => Number(row?.household?.[group]?.[gender] || 0);
  const adultMale = number('adults', 'male');
  const adultFemale = number('adults', 'female');
  const youthMale = number('youth', 'male');
  const youthFemale = number('youth', 'female');
  const childrenMale = number('children', 'male');
  const childrenFemale = number('children', 'female');
  return {
    adultMale, adultFemale, youthMale, youthFemale, childrenMale, childrenFemale,
    male: adultMale + youthMale + childrenMale,
    female: adultFemale + youthFemale + childrenFemale,
    total: Number(row?.totalAttendance ?? row?.count ?? 0)
  };
};

const demographicTotals = (rows) => rows.reduce((totals, row) => {
  const household = householdValues(row);
  Object.keys(totals).forEach((key) => { totals[key] += household[key]; });
  return totals;
}, { adultMale: 0, adultFemale: 0, youthMale: 0, youthFemale: 0, childrenMale: 0, childrenFemale: 0, male: 0, female: 0, total: 0 });

const filtersText = (filters = {}) => Object.entries(filters)
  .filter(([, value]) => value && value !== 'ALL')
  .map(([key, value]) => `${words(key)}: ${words(value)}`).join(' | ') || 'All attendance records';

const loadLogo = async () => {
  try {
    const response = await fetch('/img/logo.png');
    if (!response.ok) return null;
    const blob = await response.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (_) {
    return null;
  }
};

const footer = (doc) => {
  const height = doc.internal.pageSize.getHeight();
  doc.setDrawColor(226, 232, 240);
  doc.line(14, height - 15, 196, height - 15);
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('Generated by Jerur Church Management System', 14, height - 9);
  doc.text('Confidential - For Church Leadership Use Only', 196, height - 9, { align: 'right' });
};

const section = (doc, text, y) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...BRAND);
  doc.text(text, 14, y);
};

export const exportAttendanceSummaryPdf = async ({ churchName, serviceName, startDate, endDate, generatedAt, generatedBy, rows, filters }) => {
  const [{ jsPDF }, tableModule] = await Promise.all([import('jspdf'), import('jspdf-autotable')]);
  const autoTable = tableModule.default;
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const logo = await loadLogo();
  const totals = demographicTotals(rows);
  const attentionCount = rows.filter((row) => ATTENTION.includes(row?.attendanceOutcome) || row?.wantsPastorContact).length;
  const tableOptions = { theme: 'grid', headStyles: { fillColor: BRAND }, styles: { fontSize: 9 } };

  doc.setFillColor(...BRAND);
  doc.rect(0, 0, 210, 35, 'F');
  doc.setFillColor(...ACCENT);
  doc.rect(0, 35, 210, 2, 'F');
  if (logo) doc.addImage(logo, 'PNG', 14, 8, 18, 18);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('Attendance Report', 38, 16);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`${churchName || 'Church'} | ${serviceName || 'Service'}`, 38, 23);

  autoTable(doc, {
    body: [
      ['Date range', `${dateText(startDate)} - ${dateText(endDate || startDate)}`],
      ['Generated', dateText(generatedAt, true)], ['Generated by', generatedBy || 'System'],
      ['Filters', filtersText(filters)]
    ],
    startY: 44, theme: 'plain', styles: { fontSize: 9, cellPadding: 1.5 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 28 } }
  });

  section(doc, 'Summary', doc.lastAutoTable.finalY + 7);
  autoTable(doc, { ...tableOptions, head: [['Submissions', 'Total People', 'Male', 'Female', 'Need Attention']], body: [[rows.length, totals.total, totals.male, totals.female, attentionCount]], startY: doc.lastAutoTable.finalY + 10 });
  section(doc, 'Household Demographics', doc.lastAutoTable.finalY + 7);
  autoTable(doc, { ...tableOptions, head: [['Group', 'Male', 'Female', 'Total']], body: [
    ['Adults', totals.adultMale, totals.adultFemale, totals.adultMale + totals.adultFemale],
    ['Youth', totals.youthMale, totals.youthFemale, totals.youthMale + totals.youthFemale],
    ['Children', totals.childrenMale, totals.childrenFemale, totals.childrenMale + totals.childrenFemale]
  ], startY: doc.lastAutoTable.finalY + 10 });
  section(doc, 'Attendance Status', doc.lastAutoTable.finalY + 7);
  autoTable(doc, { ...tableOptions, head: [['Status', 'Submissions']], body: STATUSES.map((status) => [words(status), rows.filter((row) => row?.attendanceOutcome === status).length]), startY: doc.lastAutoTable.finalY + 10 });
  section(doc, 'Detailed Attendance', doc.lastAutoTable.finalY + 7);
  autoTable(doc, {
    ...tableOptions,
    head: [['Member', 'Status', 'People', 'Male', 'Female', 'Channel', 'Submitted']],
    body: rows.map((row) => {
      const household = householdValues(row);
      return [row.memberName || 'Unknown Member', words(row.attendanceOutcome, 'Unknown'), household.total, household.male, household.female, words(row.checkedInVia, 'Unknown'), dateText(row.submittedAt || row.checkInTime || row.createdAt, true)];
    }),
    startY: doc.lastAutoTable.finalY + 10,
    styles: { fontSize: 7, cellPadding: 2, overflow: 'linebreak' }, margin: { bottom: 20 },
    didDrawPage: () => footer(doc)
  });
  footer(doc);
  doc.save(fileName({ serviceName, startDate, endDate, extension: 'pdf' }));
};

const csvSafe = (value) => {
  let text = value === null || value === undefined ? '' : String(value);
  if (/^[=+\-@]/.test(text)) text = `'${text}`;
  return `"${text.replace(/"/g, '""')}"`;
};

export const exportAttendanceCsv = ({ serviceName, startDate, endDate, rows }) => {
  const headers = ['Service', 'Service Date', 'Member Name', 'Attendance Status', 'Household Total', 'Adult Male', 'Adult Female', 'Youth Male', 'Youth Female', 'Children Male', 'Children Female', 'Total Male', 'Total Female', 'Submission Method', 'Submitted At', 'Care Signal', 'Pastor Contact Requested', 'Member Message'];
  const records = rows.map((row) => {
    const household = householdValues(row);
    const submitted = row?.submittedAt || row?.checkInTime || row?.createdAt;
    return [serviceName || row?.serviceId?.title || 'Service', dateText(submitted), row?.memberName || 'Unknown Member', words(row?.attendanceOutcome, 'Unknown'), household.total, household.adultMale, household.adultFemale, household.youthMale, household.youthFemale, household.childrenMale, household.childrenFemale, household.male, household.female, words(row?.checkedInVia, 'Unknown'), dateText(submitted, true), words(row?.careSignal, 'None'), row?.wantsPastorContact ? 'Yes' : 'No', row?.message || ''];
  });
  const csv = `\uFEFF${[headers, ...records].map((record) => record.map(csvSafe).join(',')).join('\r\n')}`;
  const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' }));
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName({ serviceName, startDate, endDate, extension: 'csv' });
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
};
