const BRAND_PRIMARY = [16, 24, 40];
const BRAND_ACCENT = [254, 235, 53];
const STATUS_ORDER = [
  'PRESENT_IN_CHURCH',
  'JOINED_ONLINE',
  'ABSENT',
  'SICK',
  'NEEDS_PRAYER',
  'TRAVELLING',
  'WORKING',
  'FAMILY_COMMITMENT',
  'OTHER'
];
const ATTENTION_STATUSES = ['ABSENT', 'SICK', 'NEEDS_PRAYER'];
const FOOTER_LINES = [
  'Generated by Jerur Church Management System',
  'Confidential - For Church Leadership Use Only'
];

const formatWords = (value, fallback = 'None') => {
  if (!value) {
    return fallback;
  }

  return String(value)
    .toLowerCase()
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};

const formatDate = (value, options = {}) => {
  if (!value) {
    return 'N/A';
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return 'N/A';
  }

  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    ...options
  }).format(date);
};

const sanitizeFilePart = (value, fallback) => {
  const normalized = String(value || fallback)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return normalized || fallback;
};

const createFileName = ({ serviceName, serviceDate }) => {
  const servicePart = sanitizeFilePart(serviceName, 'service');
  const datePart = sanitizeFilePart(serviceDate, 'date');

  return `${servicePart}-${datePart}-attendance-summary.pdf`;
};

const loadLogoDataUrl = async () => {
  try {
    const response = await fetch('/img/logo.png');

    if (!response.ok) {
      return null;
    }

    const blob = await response.blob();

    return await new Promise((resolve, reject) => {
      const reader = new FileReader();

      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    return null;
  }
};

const getAttendanceBreakdownRows = (rows) => {
  const counts = STATUS_ORDER.reduce((accumulator, status) => ({
    ...accumulator,
    [status]: 0
  }), {});

  rows.forEach((row) => {
    if (row?.attendanceOutcome && Object.prototype.hasOwnProperty.call(counts, row.attendanceOutcome)) {
      counts[row.attendanceOutcome] += 1;
    }
  });

  return STATUS_ORDER.map((status) => [formatWords(status), counts[status] || 0]);
};

const getPastoralAttentionRows = (rows) => {
  return rows.filter((row) => {
    if (!row) {
      return false;
    }

    return ATTENTION_STATUSES.includes(row.attendanceOutcome) || Boolean(row.wantsPastorContact);
  });
};

const getAttendanceSummaryValues = ({ dashboard, rows }) => {
  const expectedMembers = dashboard?.kpis?.expectedMembers || 0;
  const attendanceSubmitted = dashboard?.kpis?.attendanceSubmitted || rows.length || 0;
  const attentionRows = getPastoralAttentionRows(rows);
  const attendanceRate = expectedMembers > 0
    ? Math.round((attendanceSubmitted / expectedMembers) * 100)
    : 0;
  const openCareCases = dashboard?.kpis?.openCareCases || rows.filter((row) => row?.hasOpenCareCase).length;

  return {
    expectedMembers,
    attendanceSubmitted,
    attendanceRate,
    membersRequiringAttention: attentionRows.length,
    openCareCases,
    summaryRows: [
      ['Expected Members', expectedMembers],
      ['Attendance Submitted', attendanceSubmitted],
      ['Attendance Rate', `${attendanceRate}%`],
      ['Members Requiring Attention', attentionRows.length],
      ['Open Care Cases', openCareCases]
    ]
  };
};

const getExecutiveSummary = ({ expectedMembers, attendanceSubmitted, attendanceRate, membersRequiringAttention }) => {
  return `${attendanceSubmitted} of ${expectedMembers} members submitted attendance (${attendanceRate}%). ${membersRequiringAttention} members require pastoral attention.`;
};

const getHeaderRows = ({ churchName, serviceName, serviceDate, generatedAt, generatedBy }) => {
  return [
    ['Church', churchName || 'Church'],
    ['Service', serviceName || 'Service'],
    ['Date', formatDate(serviceDate)],
    ['Generated', formatDate(generatedAt, { hour: '2-digit', minute: '2-digit', hour12: false })],
    ['Generated By', generatedBy || 'System']
  ];
};

const getPastoralAttentionTableRows = (rows) => {
  return getPastoralAttentionRows(rows).map((row) => ([
    row.memberName || 'Unknown Member',
    formatWords(row.attendanceOutcome, 'Unknown'),
    row.responseSummary || 'No response submitted'
  ]));
};

const drawSectionLabel = (doc, text, y) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...BRAND_PRIMARY);
  doc.text(text, 14, y);
};

const drawFooter = (doc) => {
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setDrawColor(226, 232, 240);
  doc.line(14, pageHeight - 18, 196, pageHeight - 18);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(FOOTER_LINES[0], 14, pageHeight - 11);
  doc.text(FOOTER_LINES[1], 14, pageHeight - 6);
};

const drawHeader = async (doc, headerRows) => {
  const logoDataUrl = await loadLogoDataUrl();

  doc.setFillColor(...BRAND_PRIMARY);
  doc.rect(0, 0, 210, 34, 'F');
  doc.setFillColor(...BRAND_ACCENT);
  doc.rect(0, 34, 210, 2.5, 'F');

  if (logoDataUrl) {
    doc.addImage(logoDataUrl, 'PNG', 14, 8, 18, 18);
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('Attendance Summary Report', 38, 16);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Jerur Church Management System', 38, 23);

  doc.setTextColor(...BRAND_PRIMARY);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);

  headerRows.forEach(([label, value], index) => {
    const rowY = 48 + (index * 7);

    doc.text(`${label}:`, 14, rowY);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value), 44, rowY);
    doc.setFont('helvetica', 'bold');
  });
};

const drawExecutiveSummary = (doc, text, startY) => {
  drawSectionLabel(doc, 'Executive Summary', startY);
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, startY + 4, 182, 18, 2, 2, 'FD');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const wrapped = doc.splitTextToSize(text, 172);
  doc.text(wrapped, 19, startY + 12);
};

export const exportAttendanceSummaryPdf = async ({ churchName, serviceName, serviceDate, generatedAt, generatedBy, dashboard, rows }) => {
  const [jspdfModule, autoTableModule] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable')
  ]);
  const { jsPDF } = jspdfModule;
  const autoTable = autoTableModule.default;
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const headerRows = getHeaderRows({ churchName, serviceName, serviceDate, generatedAt, generatedBy });
  const summaryValues = getAttendanceSummaryValues({ dashboard, rows });
  const breakdownRows = getAttendanceBreakdownRows(rows);
  const attentionRows = getPastoralAttentionTableRows(rows);
  const executiveSummary = getExecutiveSummary(summaryValues);

  await drawHeader(doc, headerRows);
  drawExecutiveSummary(doc, executiveSummary, 86);
  drawSectionLabel(doc, 'Attendance Summary', 114);

  autoTable(doc, {
    head: [['Metric', 'Value']],
    body: summaryValues.summaryRows,
    startY: 117,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { bottom: 24 }
  });

  drawSectionLabel(doc, 'Attendance Breakdown', doc.lastAutoTable.finalY + 5);
  autoTable(doc, {
    head: [['Status', 'Count']],
    body: breakdownRows,
    startY: doc.lastAutoTable.finalY + 8,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { bottom: 24 }
  });

  drawSectionLabel(doc, 'Members Requiring Pastoral Attention', doc.lastAutoTable.finalY + 5);
  autoTable(doc, {
    head: [['Member', 'Attendance Status', 'Member Response / Reason']],
    body: attentionRows.length ? attentionRows : [['No members require pastoral attention for the selected filters.', '', '']],
    startY: doc.lastAutoTable.finalY + 8,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3, cellWidth: 'wrap', overflow: 'linebreak' },
    headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 52 },
      1: { cellWidth: 40 },
      2: { cellWidth: 90 }
    },
    margin: { bottom: 24 },
    didDrawPage: () => {
      drawFooter(doc);
    }
  });

  drawFooter(doc);
  doc.save(createFileName({ serviceName, serviceDate }));
};
