import { getDonationTypeLabel, getPaymentMethodLabel } from './donationConstants';

const BRAND_PRIMARY = [16, 24, 40];
const BRAND_ACCENT = [254, 235, 53];
const FOOTER_LINES = [
  'Generated by Jerur Church Management System',
  'Confidential - For Church Leadership Use Only'
];

const formatCurrency = (value) => new Intl.NumberFormat('en-GB', {
  style: 'currency',
  currency: 'GBP'
}).format(Number(value || 0));

const formatDate = (value) => {
  if (!value) {
    return 'N/A';
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return 'N/A';
  }

  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric'
  }).format(date);
};

const sanitizeFilePart = (value, fallback) => {
  const normalized = String(value || fallback)
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return normalized || fallback;
};

const createFileName = ({ type, reportPeriod }) => {
  const reportPart = sanitizeFilePart(reportPeriod, 'all-dates');
  return `donations-${reportPart}.${type}`;
};

const loadLogoDataUrl = async () => {
  try {
    const response = await fetch('/img/logo.png');

    if (!response.ok) {
      return null;
    }

    const blob = await response.blob();

    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (error) {
    return null;
  }
};

const downloadBlob = (blob, fileName) => {
  const url = window.URL.createObjectURL(blob);
  const anchor = document.createElement('a');

  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  window.URL.revokeObjectURL(url);
};

const drawFooter = (doc) => {
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setDrawColor(226, 232, 240);
  doc.line(14, pageHeight - 18, 196, pageHeight - 18);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(FOOTER_LINES[0], 14, pageHeight - 11);
  doc.text(FOOTER_LINES[1], 14, pageHeight - 6);
};

const drawSectionLabel = (doc, text, y) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...BRAND_PRIMARY);
  doc.text(text, 14, y);
};

const drawHeader = async (doc, { churchName, reportPeriod, selectedDonationType, selectedPaymentMethod, generatedAt }) => {
  const logoDataUrl = await loadLogoDataUrl();

  doc.setFillColor(...BRAND_PRIMARY);
  doc.rect(0, 0, 210, 34, 'F');
  doc.setFillColor(...BRAND_ACCENT);
  doc.rect(0, 34, 210, 2.5, 'F');

  if (logoDataUrl) {
    doc.addImage(logoDataUrl, 'PNG', 14, 8, 18, 18);
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('Donation Report', 38, 16);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Jerur Church Management System', 38, 23);

  const headerRows = [
    ['Church', churchName || 'Church'],
    ['Report Period', reportPeriod || 'All Dates'],
    ['Donation Type', selectedDonationType || 'All Donation Types'],
    ['Payment Method', selectedPaymentMethod || 'All Payment Methods'],
    ['Generated', formatDate(generatedAt)]
  ];

  doc.setTextColor(...BRAND_PRIMARY);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);

  headerRows.forEach(([label, value], index) => {
    const rowY = 48 + (index * 7);
    doc.text(`${label}:`, 14, rowY);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value), 52, rowY);
    doc.setFont('helvetica', 'bold');
  });
};

export const exportDonationReportPdf = async ({
  churchName,
  reportPeriod,
  selectedDonationType,
  selectedPaymentMethod,
  summary,
  rows,
  generatedAt
}) => {
  const [jspdfModule, autoTableModule] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable')
  ]);
  const { jsPDF } = jspdfModule;
  const autoTable = autoTableModule.default;
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  await drawHeader(doc, {
    churchName,
    reportPeriod,
    selectedDonationType,
    selectedPaymentMethod,
    generatedAt
  });

  drawSectionLabel(doc, 'Summary', 86);
  autoTable(doc, {
    head: [['Metric', 'Value']],
    body: [
      ['Total Donations', formatCurrency(summary?.totalAmount)],
      ['Online Donations', formatCurrency(summary?.onlineAmount)],
      ['Offline Donations', formatCurrency(summary?.offlineAmount)],
      ['Total Transactions', summary?.transactionCount || 0]
    ],
    startY: 89,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3 },
    headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { bottom: 24 }
  });

  drawSectionLabel(doc, 'Filtered Donations', doc.lastAutoTable.finalY + 6);
  autoTable(doc, {
    head: [['Date', 'First Name', 'Last Name', 'Donation Type', 'Amount', 'Payment Method']],
    body: rows.length
      ? rows.map((row) => ([
        formatDate(row.date_donated),
        row.first_name || '-',
        row.last_name || '-',
        getDonationTypeLabel(row.donation_type),
        formatCurrency(row.amount),
        getPaymentMethodLabel(row.online)
      ]))
      : [['No donations matched the selected filters.', '', '', '', '', '']],
    startY: doc.lastAutoTable.finalY + 9,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3, overflow: 'linebreak' },
    headStyles: { fillColor: BRAND_PRIMARY, textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { bottom: 24 },
    didDrawPage: () => {
      drawFooter(doc);
    }
  });

  drawFooter(doc);
  doc.save(createFileName({ type: 'pdf', reportPeriod }));
};

export const exportDonationReportCsv = ({ reportPeriod, rows }) => {
  const headers = ['Date', 'First Name', 'Last Name', 'Donation Type', 'Amount', 'Payment Method'];
  const bodyRows = rows.map((row) => ([
    formatDate(row.date_donated),
    row.first_name || '',
    row.last_name || '',
    getDonationTypeLabel(row.donation_type),
    String(Number(row.amount || 0).toFixed(2)),
    getPaymentMethodLabel(row.online)
  ]));
  const csv = [headers, ...bodyRows]
    .map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(','))
    .join('\n');

  downloadBlob(new Blob([csv], { type: 'text/csv;charset=utf-8;' }), createFileName({ type: 'csv', reportPeriod }));
};